# Generated by Django 3.0.6 on 2021-10-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='categories',
            field=models.ManyToManyField(to='clothes.Category'),
        ),
    ]
